services:
  app:
    image: homepedia_app:latest
    env_file:
      - .env
    ports:
      - '3000:3000'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:1.23.4-alpine
    env_file:
      - .env
    ports:
      - '${NGINX_PORT}:${NGINX_PORT}'
    volumes:
      - ./nginx/default_production.conf:/etc/nginx/templates/default.conf.template:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/wait_for_app_start.sh:/wait_for_app_start.sh
    entrypoint: /bin/sh -c "./wait_for_app_start.sh ${APP_FULL_DOMAIN}"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure