services:
  app:
    build: ./app
    container_name: '${APP_HOST}'
    restart: 'no'
    security_opt:
     - no-new-privileges:false
    expose:
      - '${APP_PORT}'
    networks:
      - app-network
    env_file:
      - .env
    volumes:
      - ./app:/homepedia_app

  nginx:
    image: nginx:1.23.4-alpine
    restart: 'no'
    security_opt:
     - no-new-privileges:false
    ports:
      - '${NGINX_PORT}:${NGINX_PORT}'
    depends_on:
      - app
    volumes:
      - ./nginx/default_production.conf:/etc/nginx/templates/default.conf.template:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app:/home/nginx/app:ro
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge